### ISSUE TITLE
the description misspells "program"

### ISSUE THREAD

**Issue by ebenz99** [ethinallen/doNotGetDropped#1]
right now it says "progrma"

**Comment by ethinallen** [comment]
fixed! thanks ebenz99

**Comment by ebenz99** [comment]
![image](https://user-images.githubusercontent.com/24685106/64701934-aa9b1e00-d477-11e9-9c98-f57295dcad5e.png)

Coming back to say this is still a problem. Recommend reopening this issue and assigning @ethinallen for escalation.

**Comment by ethinallen** [comment]
I changed the markdown and not the description itself. I've issued myself a write-up and will subject myself to vicious code reviews biweekly for the next three months.

**Comment by ethinallen** [comment]
I made the appropriate changes, I believe this is a suitable fix. Assigning @ebenz99 as the repo owner because I am clearly incompetent.
